### ISSUE TITLE
(question) assigning sliders to sonar

### ISSUE THREAD

**Issue by franfran07** [TotalPanther317/steelseries-sonar-api#1]
Hey, great project !

In your tutorial you are not mentioning how to assign the sliders to a specific channel in sonar. Or maybe i missed it ?

**Comment by TotalPanther317** [comment]
Thanks.

They are hardcoded to the midi channels in main.py lines 40-72.

`if midi.getControllerNumber() == 2:
            sonar.set_volume('chatRender', converted)`

This assigned midi channel 2 to chatRender. I would recommend switching around the channel numbers for changing this.

I will implement a system to adjust these in a config file along other things in the future. This issue will be closed when added.
