### ISSUE TITLE
name 'rtmidi' is not defined

### ISSUE THREAD

**Issue by franfran07** [TotalPanther317/steelseries-sonar-api#3]
Hey ! I'm finally trying your api ! Unfortunately, i get this error when trying to run it. Am i doing something wrong ?

![Capture d'écran 2024-10-22 001123](https://github.com/user-attachments/assets/57ed8010-932a-4a95-ae09-8daef5e315ce)

**Comment by TotalPanther317** [comment]
Did you `pip3 install rtmidi`?

**Comment by franfran07** [comment]
yes, i did.
![Capture d'écran 2024-10-22 194122](https://github.com/user-attachments/assets/220889cd-412c-4bca-92ac-5d3535c72cdf)

**Comment by TotalPanther317** [comment]
Try running python in terminal and `import rtmidi`.

**Comment by franfran07** [comment]
I think the issue is that there is a # in main at line 3 after json. Correct me if i'm wrong.

**Comment by TotalPanther317** [comment]
I don't know why this made it in the code but it is now gone.
